import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <script defer src="https://api.pirsch.io/pa.js"
    id="pianjs"
    data-code="31jEKw3aG6dreCdq0ZobcTWelRXztm9c"></script>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
